apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: my-wf-tmple
spec:
  event:
    selector: |
      payload.action == "labeled" && payload.label.name == "argo-wf/my-wf-tmple" && payload.labels != ""
  submit:
    workflowTemplateRef:
      name: my-wf-tmple
    arguments:
      parameters:
      - name: message
        valueFrom:
          event: "filter(payload.pull_request.labels, {.name == 'bug'})"
