apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-wf
  namespace: argo-workflows
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argo-workflows-server
            port:
              number: 2746
