---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-workflow-crud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-crud
subjects:
- kind: ServiceAccount
  name: test
  namespace: argo-workflows
