apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-test-logview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logview
subjects:
- kind: ServiceAccount
  name: test
  namespace: argo-workflows
