---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
    - ""
  resources:
  - pods
  - pods/log
  verbs: ["get", "list", "watch"]
