---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-crud
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  
