---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    name: ''
    namespace: argo-workflows
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-workflows-with-argocd-dex/workflows
    repoURL: 'https://github.com/toyamagu-2021/argo-workflows-sso.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
