environments:
  default:
    values:
    - createWorkflowDefaults: true
  withought-workflow-defaults:
    values:
    - createWorkflowDefaults: false
  

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
# ArgoWF本体
- name: argo-workflows
  namespace: argo-workflows
  chart: argo/argo-workflows
  values:
  - argo-workflows/values.yaml.gotmpl
# ArgoWFアクセス用ユーザー
- name: user
  namespace: argo-workflows
  chart: ./user
- name: workflows
  namespace: argo-workflows
  chart: ./workflows
