---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-wf-admin
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-wf-admin
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  
  