# repositories:
#   - name: argo
#     url: https://argoproj.github.io/argo-helm

releases:
# ArgoWF本体
- name: argo-workflows
  namespace: argo
  chart: argo/argo-workflows
  values:
  - argo-workflows/values.yaml
# Ingress
- name: ingress
  chart: ./ingress
# ArgoWFアクセス用ユーザー
- name: user
  namespace: argo
  chart: ./user
# Webhook用のリソース
- name: webhook-resources
  namespace: argo
  chart: ./github
# WebhookでトリガーされるWorkflow
- name: workflow-templates
  namespace: argo
  chart: ./workflow-templates
